<a href="https://colab.research.google.com/github/benvekedim/machine-learning-101/blob/main/kategorik.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#veri yukleme
veriler = pd.read_csv('https://bilkav.com/eksikveriler.csv')
#veriler

#veri on isleme

boy = veriler[['boy']]
print(boy)

boykilo = veriler[['boy','kilo']]
print(boykilo)




    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166
    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


In [2]:
class insan:
    boy = 180
    def kosmak(self,b):
        return b + 10

ali = insan()
print(ali.boy)
print(ali.kosmak(90))

180
100


In [3]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

Yas = veriler.iloc[:,1:4].values
print(Yas)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]


In [4]:
imputer = imputer.fit(Yas[:,1:4])
Yas[:,1:4] = imputer.transform(Yas[:,1:4])
print(Yas)


[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


In [6]:
veriler.head()

ulke  boy  kilo   yas cinsiyet
0   tr  130    30  10.0        e
1   tr  125    36  11.0        e
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k
4   tr  129    38  12.0        e

In [5]:
ulke = veriler.iloc[:,0:1].values
print(ulke)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]


In [8]:
veriler.iloc[:,0]

0     tr
1     tr
2     tr
3     tr
4     tr
5     tr
6     tr
7     tr
8     tr
9     us
10    us
11    us
12    us
13    us
14    us
15    fr
16    fr
17    fr
18    fr
19    fr
20    fr
21    fr
Name: ulke, dtype: object

In [9]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [10]:
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
# np unique ile ulke dizisine al
# sırala : output ['fr','tr','us'] 
# LabelEncoder için fr:0  tr:1 us:2 label ver
# OneHotEncoder için fr: [1,0,0], tr:[0,1,0] us:[0,0,1] label ver

In [11]:
veriler.head()

ulke  boy  kilo   yas cinsiyet
0   tr  130    30  10.0        e
1   tr  125    36  11.0        e
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k
4   tr  129    38  12.0        e

In [15]:
country = [i[0] for i in np.array(veriler)]
unique_country = sorted(np.unique(country))
unique_country 

['fr', 'tr', 'us']

In [19]:
# for i in country:
#   print(i)

In [17]:
def lab_encoder(veriler):
  encoder = []

  country = [i[0] for i in np.array(veriler)]
  unique_country = sorted(np.unique(country))
  for i in country:
    if i == unique_country[0]:
      encoder.append(0)
    elif i == unique_country[1]:
      encoder.append(1)
    else:
      encoder.append(2)
  
  return encoder

lab_encoder(veriler)


[1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0]

In [18]:
def one_hot_encoder(veriler):
  one_hot_encoder = []

  country = [i[0] for i in np.array(veriler)]
  unique_country = sorted(np.unique(country))
  for i in country:
    if i == unique_country[0]:
      one_hot_encoder.append([1,0,0])
    elif i == unique_country[1]:
      one_hot_encoder.append([0,1,0])
    else:
      one_hot_encoder.append([0,0,1])

  return one_hot_encoder

one_hot_encoder(veriler)

[[0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0]]