<a href="https://colab.research.google.com/github/benvekedim/machine-learning-101/blob/main/data-Preprocessing/eksikVeriler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#veri yukleme
veriler = pd.read_csv('https://bilkav.com/eksikveriler.csv')
#veriler

#veri on isleme

boy = veriler[['boy']]
print(boy)

boykilo = veriler[['boy','kilo']]
print(boykilo)




    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166
    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


In [ ]:
veriler.head()

ulke  boy  kilo   yas cinsiyet
0   tr  130    30  10.0        e
1   tr  125    36  11.0        e
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k
4   tr  129    38  12.0        e

In [ ]:
class insan:
    boy = 180
    def kosmak(self,b):
        return b + 10

ali = insan()
print(ali.boy)
print(ali.kosmak(90))

180
100


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
Yas = veriler.iloc[:,1:4].values
print(Yas)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]


In [ ]:
imputer = imputer.fit(Yas[:,1:4])
Yas[:,1:4] = imputer.transform(Yas[:,1:4])
print(Yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


In [ ]:
np.mean(veriler[['yas']])

yas    28.45
dtype: float64

In [ ]:
#1d dizide nan değerleri ortalamayla değiştirme
age = np.array([i[3] for i in np.array(veriler)])
age

array([10., 11., 10.,  9., 12., 30., 25., 35., 22., 33., 27., 44., nan,
       41., 55., 47., nan, 27., 28., 29., 32., 42.])

In [ ]:
col_mean = np.nanmean(age,axis=0)
col_mean

28.45

In [ ]:
inds = np.argwhere(np.isnan(age))
inds

array([[12],
       [16]])

In [ ]:
age[inds] = col_mean
age

array([10.  , 11.  , 10.  ,  9.  , 12.  , 30.  , 25.  , 35.  , 22.  ,
       33.  , 27.  , 44.  , 28.45, 41.  , 55.  , 47.  , 28.45, 27.  ,
       28.  , 29.  , 32.  , 42.  ])